// Compiles UnoCSS output ahead of time into a string module
// (`app/embed/.generated/css.ts`) that the embed's custom element adopts into its
// shadow root, so it stays styled inside github.com's page with no leakage either way.
// Modeled on devframe's `design/build-shadow-css.ts` (`hub-ui`/`json-render-ui` use the
// same pipeline for their own shadow-root surfaces).
import { Buffer } from 'node:buffer'
import fs from 'node:fs/promises'
import { createRequire } from 'node:module'
import { join } from 'node:path'
import process from 'node:process'
import { fileURLToPath } from 'node:url'
import { transform } from 'lightningcss'
import { glob } from 'tinyglobby'
import { createGenerator } from 'unocss'
import { createUnoConfig } from '../uno.config'

// Story-only utility classes must not leak into the shipped shadow-root stylesheet.
const IGNORE = ['**/*.stories.*', '**/__tests__/**']

// `@antfu/design` semantic tokens the embed needs guaranteed present: Wind3 drops a
// *plain* shortcut (`bg-base`) from the main extraction pass when it also appears
// variant-prefixed elsewhere (e.g. `dark:bg-...`). Safelisting forces both variants.
const SURFACE_SAFELIST = [
  'bg-base',
  'bg-secondary',
  'bg-active',
  'bg-hover',
  'color-base',
  'color-muted',
  'color-faint',
  'color-active',
  'border-base',
]

// Rename Wind's internal `--un-*` vars to a private prefix - a Wind4 host page's
// document-wide `@property --un-*` registrations would otherwise make our unitless,
// Wind3-authored declarations of the same names invalid.
function namespaceShadowCssVars(css: string): string {
  return css.replaceAll('--un-', '--un-diffs-embed-')
}

export async function buildEmbedCSS() {
  const root = fileURLToPath(new URL('..', import.meta.url))
  const embedDir = join(root, 'src/embed')
  const require = createRequire(import.meta.url)

  const config = createUnoConfig()
  const generator = await createGenerator(config)

  const files = await glob(['src/**/*.{vue,ts}'], {
    cwd: root,
    absolute: true,
    ignore: IGNORE,
  })

  // The embed reuses `@antfu/design`'s Vue components (buttons, form controls, …)
  // directly. UnoCSS ignores `node_modules` by default, so their own semantic
  // shortcut classes would be absent from the shadow-root stylesheet otherwise.
  // `utils/` holds the `@unocss-include` files (the file-icon class table, among others).
  const designDir = join(require.resolve('@antfu/design/package.json'), '..')
  const designFiles = await glob(['components/**/*.vue', 'utils/*.ts'], {
    cwd: designDir,
    absolute: true,
    ignore: IGNORE,
  })

  const tokens = new Set<string>()
  for (const file of [...files, ...designFiles]) {
    const content = await fs.readFile(file, 'utf-8')
    await generator.applyExtractors(content, file, tokens)
  }

  const reset = await fs.readFile(require.resolve('@unocss/reset/tailwind.css'), 'utf-8')
  // vue-afloat mounts poppers into the shadow root and declares its tokens on `:host` too.
  const afloatCss = await fs.readFile(require.resolve('vue-afloat/style.css'), 'utf-8')
  const mainCss = await fs.readFile(join(root, 'src/main.css'), 'utf-8')

  const { css: unoCss } = await generator.generate(tokens)
  // Dedicated pass for the surface safelist (see its own comment) - always present,
  // even for tokens the extractor above missed in a dynamically-assembled string.
  const { css: surfacesCss } = await generator.generate(SURFACE_SAFELIST.join(' '))

  let css = [reset, afloatCss, mainCss, unoCss, surfacesCss].join('\n')
  css = namespaceShadowCssVars(css)
  css = transform({
    filename: 'diffs-embed.css',
    code: Buffer.from(css),
    minify: true,
  }).code.toString()

  const outDir = join(embedDir, '.generated')
  await fs.mkdir(outDir, { recursive: true })
  await fs.writeFile(join(outDir, 'css.ts'), [
    '// Generated by scripts/build-embed-css.ts - do not edit by hand.',
    `export default ${JSON.stringify(css)}`,
    '',
  ].join('\n'))

  process.stdout.write(`✓ embed CSS built (${files.length + designFiles.length} sources scanned, ${(css.length / 1024).toFixed(1)} kB)\n`)
}
