/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

// Custom route params parsers
type Param_localBranch = _ExtractParamParserType<typeof import('./src/params/local-branch.ts').parser>
type Param_localCommit = _ExtractParamParserType<typeof import('./src/params/local-commit.ts').parser>
type Param_localRange = _ExtractParamParserType<typeof import('./src/params/local-range.ts').parser>
type Param_pr = _ExtractParamParserType<typeof import('./src/params/pr.ts').parser>
type Param_range = _ExtractParamParserType<typeof import('./src/params/range.ts').parser>

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {
      'local-branch': { type: Param_localBranch }
      'local-commit': { type: Param_localCommit }
      'local-range': { type: Param_localRange }
      'pr': { type: Param_pr }
      'range': { type: Param_range }
    }
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'local-branch': RouteRecordInfo<
      'local-branch',
      '/branch/:branch',
      { 'branch': Exclude<Param_localBranch, unknown[] | null> },
      { 'branch': Exclude<Param_localBranch, unknown[] | null> },
      | never
    >,
    'local-commit': RouteRecordInfo<
      'local-commit',
      '/commit/:sha',
      { 'sha': Exclude<Param_localCommit, unknown[] | null> },
      { 'sha': Exclude<Param_localCommit, unknown[] | null> },
      | never
    >,
    'local-compare': RouteRecordInfo<
      'local-compare',
      '/compare/:range',
      { 'range': Exclude<Param_localRange, unknown[] | null> },
      { 'range': Exclude<Param_localRange, unknown[] | null> },
      | never
    >,
    '/gh/[owner]/[repo]/': RouteRecordInfo<
      '/gh/[owner]/[repo]/',
      '/gh/:owner/:repo',
      { 'owner': string, 'repo': string },
      { 'owner': string, 'repo': string },
      | never
    >,
    'github-pr': RouteRecordInfo<
      'github-pr',
      '/gh/:owner/:repo/:number',
      { 'number': Exclude<Param_pr, unknown[] | null>, 'owner': string, 'repo': string },
      { 'number': Exclude<Param_pr, unknown[] | null>, 'owner': string, 'repo': string },
      | never
    >,
    'github-commit': RouteRecordInfo<
      'github-commit',
      '/gh/:owner/:repo/commit/:sha',
      { 'owner': string, 'repo': string, 'sha': string },
      { 'owner': string, 'repo': string, 'sha': string },
      | never
    >,
    'github-compare': RouteRecordInfo<
      'github-compare',
      '/gh/:owner/:repo/compare/:range',
      { 'owner': string, 'range': Exclude<Param_range, unknown[] | null>, 'repo': string },
      { 'owner': string, 'range': Exclude<Param_range, unknown[] | null>, 'repo': string },
      | never
    >,
    '/upload': RouteRecordInfo<
      '/upload',
      '/upload',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'local-worktree': RouteRecordInfo<
      'local-worktree',
      '/worktree',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'packages/app/src/pages-local/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'packages/app/src/pages-local/branch/[branch=local-branch].vue': {
      routes:
        | 'local-branch'
      views:
        | never
      pathParamNames:
        | 'branch'
    }
    'packages/app/src/pages-local/commit/[sha=local-commit].vue': {
      routes:
        | 'local-commit'
      views:
        | never
      pathParamNames:
        | 'sha'
    }
    'packages/app/src/pages-local/compare/[range=local-range].vue': {
      routes:
        | 'local-compare'
      views:
        | never
      pathParamNames:
        | 'range'
    }
    'packages/app/src/pages-web/gh/[owner]/[repo]/index.vue': {
      routes:
        | '/gh/[owner]/[repo]/'
      views:
        | never
      pathParamNames:
        | never
    }
    'packages/app/src/pages-web/gh/[owner]/[repo]/[number=pr].vue': {
      routes:
        | 'github-pr'
      views:
        | never
      pathParamNames:
        | 'number'
    }
    'packages/app/src/pages-web/gh/[owner]/[repo]/commit/[sha].vue': {
      routes:
        | 'github-commit'
      views:
        | never
      pathParamNames:
        | 'sha'
    }
    'packages/app/src/pages-web/gh/[owner]/[repo]/compare/[range=range].vue': {
      routes:
        | 'github-compare'
      views:
        | never
      pathParamNames:
        | 'range'
    }
    'packages/app/src/pages-web/upload.vue': {
      routes:
        | '/upload'
      views:
        | never
      pathParamNames:
        | never
    }
    'packages/app/src/pages-local/worktree.vue': {
      routes:
        | 'local-worktree'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
