import { defineCustomElement } from 'vue'
import { installAppContext } from '../app-context'
import { i18n } from '../i18n'
// Generated by `pnpm run build:embed:css` (see scripts/build-embed-css.ts) - a
// pre-compiled, shadow-root-safe stylesheet (Wind3, reset, vue-afloat, and this app's
// own CSS all baked in), since the raw per-package stylesheets assume a normal
// document (`:root`/`html`/`body` selectors that never reach a shadow tree) and
// `virtual:uno.css?inline` doesn't resolve under this build's single-chunk output.
import diffsEmbedCss from './.generated/css'
import EmbedApp from './EmbedApp.ce.vue'

// Shadow DOM is isolated from github.com's page stylesheets entirely - push the
// generated CSS into this component's own `styles` (populated by
// `@vitejs/plugin-vue`'s `.ce.vue` compiler mode), so it lands inside the shadow root
// instead.
EmbedApp.styles ??= []
EmbedApp.styles.push(diffsEmbedCss)

// A constructor can only be registered once, hence one `defineCustomElement` per tag.
function defineEmbedPanel() {
  return defineCustomElement(EmbedApp, {
    configureApp: (app) => {
      app.use(i18n)
      installAppContext(app)
    },
  })
}

customElements.define('pulls-review-embed-panel', defineEmbedPanel())

// Backward compatibility, remove this later
customElements.define('diffs-embed-panel', defineEmbedPanel())
