name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    uses: sxzz/workflows/.github/workflows/release.yml@main
    with:
      publish: true
      build: pnpm -F @pulls.review/core -F @pulls.review/actions -F pulls.review run build
    permissions:
      contents: write
      id-token: write
